name: 'Notify Area Owners to Triage Issues'

on:
  workflow_dispatch: 

permissions:
  issues: write
  contents: read
  
jobs:
  notify-area-owners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Notify area owners about issues waiting for triage
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const untriagedLabel = 'untriaged';  // The label indicating the issue needs triage
            const daysWithoutAction = 7;  // If the issue is in triage for more than 7 days
            const issues = await github.paginate(github.rest.issues.listForRepo, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: untriagedLabel,
              state: 'open',
            });

            for (const issue of issues) {
              const issueCreatedAt = new Date(issue.created_at);
              const currentTime = new Date();
              const timeSinceCreated = currentTime - issueCreatedAt;
              const timeThreshold = 8 * 1000; // Convert days to milliseconds

              // Check if the issue has been in the untriaged state for more than the threshold (7 days)
              if (timeSinceCreated > timeThreshold) {
                // Send a reminder comment to the issue if it exceeds the threshold
                const commentBody = `🚨 Reminder: This issue has been in the "triage" state for over a week and hasn't been triaged yet. Please review it.`;
                
                // Add a comment to the issue
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  body: commentBody
                });

                console.log(`Notified area owner about issue #${issue.number} awaiting triage.`);
              }
            }
